label_dict <- list(
  "(Intercept)" ="Constant",
  #"Constant"="Constant",
  "percent_suburban"="% Population Suburban",
  "GDP_percapita"="GDP ('000) per capita, chained 2017",
  "pct_workers_age55_older"="% 55+years",
  "pct_workers_income1250_less"="% Income<1250", 
  "pct_workers_white"="% White", 
  "pct_workers_education_college"="% College Educated", 
  "pct_workers_education_lesshighschool"="% Less than High School",
  "pct_workers_female"="% Female",
  "pct_workers_AgriMiningUtilCons"="% Work in Agriculture/Mining etc", 
  "pct_workers_Manuf"="% Work in Manufacturing", 
  "pct_workers_TradeCommerceTransport"="% Work in Trade/Commerce/Transport",
  "pct_workers_InfoFinProf_services"="% Work in Professional Services",
  "pct_workers_PublicSocial_services"="% Work in Public/Social Services",
  "pct_workers_Entertainment"="% Work in Entertainment/Recreation",
  'average_time_work'="Work commute (mins)", 
  "percent_publictransport"="Percent commuters using transit",
  "delta_pct_ptcar_longcommute" ="Difference in %commutes >=45min",
  "pct_carcommutes_over45m"="% car commutes >=45min",
  "pct_ptcommutes_over45m"="% public transport commutes >=45min",

  "distance_k"= "Road length ('000 km)",
  "num_nodes"= "Number of Road Intersections",
  "mean_local_gridness"="Griddedness of road network",
  "all_bua"="Built Up Area",
  
  "popdensity_1000persqkm"="Population Density('000/km2)",
  "total_pop" = "Total Residential Population",
  "percent_white"="Percent White of Resi Pop", 
  "delta_nonwhite_white_unemployed"="Difference in NonWhite-White Unemployment Rates" ,
  "gini" ="Gini Income Inequality Score", 
  "percent_unemployed" ="Percent Labor Force Unemployed",
  "pct_workers_female" ="Percent Labor Force Women",
  
  "multigroupd_race_rac"= "Residential Racial Seg",
  "multigroupd_race_rac_acs"="Residential Racial Seg, ACS estimates",
  "d_nonhispanichispanic_rac"="Residential Ethnic Seg",

  "multigroupd_education_rac"= "Residential Class Seg",
  "multigroupd_education_rac_acs"="Residential Class Seg, ACS estimates", 
  "multigroupd_race_wac"= "Workhood Racial Seg Score",
  "multigroupd_race_wac_NC"= "Workhood Racial Seg Score",
  "d_nonhispanichispanic_wac"="Workhood Ethnic Seg",
  "d_nonhispanichispanic_wac_NC"="Workhood Ethnic Seg",
  
  "multigroupd_education_wac"= "Workhood Class Seg Score",
  "multigroupd_education_wac_NC"= "Workhood Class Seg Score",
  
  ## interactions between racial seg & modifiers
  "multigroupd_race_rac:pct_workers_age55_older"="Residential Racial Seg:% 55+years",
  "multigroupd_race_rac:pct_workers_income1250_less"="Residential Racial Seg:% Income<1250", 
  "multigroupd_race_rac:pct_workers_white"="Residential Racial Seg:% White", 
  "multigroupd_race_rac:pct_workers_education_college"="Residential Racial Seg:% College Educated", 
  "multigroupd_race_rac:pct_workers_education_lesshighschool"="Residential Racial Seg:% Less than High School",
  "multigroupd_race_rac:pct_workers_AgriMiningUtilCons"="Residential Racial Seg:% Work in Agriculture/ Mining etc", 
  "multigroupd_race_rac:pct_workers_Manuf"="Residential Racial Seg:% Work in Manufacturing", 
  "multigroupd_race_rac:pct_workers_TradeCommerceTransport"="Residential Racial Seg:% Work in Trade/Commerce/Transport",
  "multigroupd_race_rac:pct_workers_InfoFinProf_services"="Residential Racial Seg:% Work in Professional Services",
  "multigroupd_race_rac:pct_workers_PublicSocial_services"="Residential Racial Seg:% Work in Public/Social Services",
  "multigroupd_race_rac:pct_workers_Entertainment"="Residential Racial Seg:% Work in Entertainment/Recreation",
  
  'multigroupd_race_rac:average_time_work'="Residential Racial Seg:Work commute (mins)", 
  "multigroupd_race_rac:percent_publictransport"="Residential Racial Seg:%commuters using transit",
  "multigroupd_race_rac:delta_pct_ptcar_longcommute" ="Residential Racial Seg:Diff in %commutes>=45min",
  "multigroupd_race_rac:popdensity_1000persqkm"= "Residential Racial Seg:Pop Density",
  "multigroupd_race_rac:pct_carcommutes_over45m"="Residential Racial Seg:% car commutes >=45min",
  "multigroupd_race_rac:pct_ptcommutes_over45m"="Residential Racial Seg:% PT commutes >=45min",
  
  "multigroupd_race_rac:distance_k"= "Residential Racial Seg: Road length ('000 km)",
  "multigroupd_race_rac:num_nodes"= "Residential Racial Seg: Number of Intersections",

  "multigroupd_race_rac:mean_local_gridness"="Residential Racial Seg: Griddedness",
  "multigroupd_race_rac:all_bua"="Residential Racial Seg: Built Up Area",
  
  "multigroupd_race_rac:total_pop"= "Residential Racial Seg: Total Population",
  "multigroupd_race_rac:percent_white"= "Residential Racial Seg: %White",
  "multigroupd_race_rac:delta_nonwhite_white_unemployed"= "Residential Racial Seg: Diff Nonwhite-White Unemployment",
  "multigroupd_race_rac:gini"= "Residential Racial Seg:Gini",
  "multigroupd_race_rac:percent_unemployed"= "Residential Racial Seg:%Unemployment",
  
  ## interactions between racial seg & modifiers
  "multigroupd_race_rac_acs:pct_workers_age55_older"="Residential Racial Seg:% 55+years",
  "multigroupd_race_rac_acs:pct_workers_income1250_less"="Residential Racial Seg:% Income<1250", 
  "multigroupd_race_rac_acs:pct_workers_white"="Residential Racial Seg:% White", 
  "multigroupd_race_rac_acs:pct_workers_education_college"="Residential Racial Seg:% College Educated", 
  "multigroupd_race_rac_acs:pct_workers_education_lesshighschool"="Residential Racial Seg:% Less than High School",
  "multigroupd_race_rac_acs:pct_workers_AgriMiningUtilCons"="Residential Racial Seg:% Work in Agriculture/ Mining etc", 
  "multigroupd_race_rac_acs:pct_workers_Manuf"="Residential Racial Seg:% Work in Manufacturing", 
  "multigroupd_race_rac_acs:pct_workers_TradeCommerceTransport"="Residential Racial Seg:% Work in Trade/Commerce/Transport",
  "multigroupd_race_rac_acs:pct_workers_InfoFinProf_services"="Residential Racial Seg:% Work in Professional Services",
  "multigroupd_race_rac_acs:pct_workers_PublicSocial_services"="Residential Racial Seg:% Work in Public/Social Services",
  "multigroupd_race_rac_acs:pct_workers_Entertainment"="Residential Racial Seg:% Work in Entertainment/Recreation",
  
  'multigroupd_race_rac_acs:average_time_work'="Residential Racial Seg:Work commute (mins)", 
  "multigroupd_race_rac_acs:percent_publictransport"="Residential Racial Seg:%commuters using transit",
  "multigroupd_race_rac_acs:delta_pct_ptcar_longcommute" ="Residential Racial Seg:Diff in %commutes>=45min",
  "multigroupd_race_rac_acs:popdensity_1000persqkm"= "Residential Racial Seg:Pop Density",
  "multigroupd_race_rac_acs:pct_carcommutes_over45m"="Residential Racial Seg:% car commutes >=45min",
  "multigroupd_race_rac_acs:pct_ptcommutes_over45m"="Residential Racial Seg:% PT commutes >=45min",
  
  "multigroupd_race_rac_acs:total_pop"= "Residential Racial Seg: Total Population",
  "multigroupd_race_rac_acs:percent_white"= "Residential Racial Seg: %White",
  "multigroupd_race_rac_acs:delta_nonwhite_white_unemployed"= "Residential Racial Seg: Diff Nonwhite-White Unemployment",
  "multigroupd_race_rac_acs:gini"= "Residential Racial Seg:Gini",
  "multigroupd_race_rac_acs:percent_unemployed"= "Residential Racial Seg:%Unemployment",
  

  ### educational seg and interaction with modifiers 
  "multigroupd_education_rac:pct_workers_age55_older"="Residential Class Seg:% 55+years",
  "multigroupd_education_rac:pct_workers_income1250_less"="Residential Class Seg:% Income<1250", 
  "multigroupd_education_rac:pct_workers_white"="Residential Class Seg:% White", 
  "multigroupd_education_rac:pct_workers_education_college"="Residential Class Seg:% College Educated", 
  "multigroupd_education_rac:pct_workers_education_lesshighschool"="Residential Class Seg:% Less than High School",
  "multigroupd_education_rac:pct_workers_AgriMiningUtilCons"="Residential Class Seg:% Work in Agriculture/ Mining etc", 
  "multigroupd_education_rac:pct_workers_Manuf"="Residential Class Seg:% Work in Manufacturing", 
  "multigroupd_education_rac:pct_workers_TradeCommerceTransport"="Residential Class Seg:% Work in Trade/Commerce/Transport",
  "multigroupd_education_rac:pct_workers_InfoFinProf_services"="Residential Class Seg:% Work in Professional Services",
  "multigroupd_education_rac:pct_workers_PublicSocial_services"="Residential Class Seg:% Work in Public/Social Services",
  "multigroupd_education_rac:pct_workers_Entertainment"="Residential Class Seg:% Work in Entertainment/Recreation",
  
  'multigroupd_education_rac:average_time_work'="Residential Class Seg:Work commute (mins)", 
  "multigroupd_education_rac:percent_publictransport"="Residential Class Seg:%commuters using transit",
  "multigroupd_education_rac:delta_pct_ptcar_longcommute" ="Residential Class Seg:Diff in %commutes>=45min",
  "multigroupd_education_rac:popdensity_1000persqkm"= "Residential Class Seg:Pop Density",
  "multigroupd_education_rac:pct_carcommutes_over45m"="Residential Class Seg:% car commutes >=45min",
  "multigroupd_education_rac:pct_ptcommutes_over45m"="Residential Class Seg:% PT commutes >=45min",
  
  "multigroupd_education_rac:distance_k"= "Residential Class Seg: Road length ('000 km)",
  "multigroupd_education_rac:num_nodes"= "Residential Class Seg: Number of Intersections",
  "multigroupd_education_rac:mean_local_gridness"="Residential Class Seg: Griddedness",
  "multigroupd_education_rac:all_bua"="Residential Class Seg: Built Up Area",
  
  "multigroupd_education_rac:total_pop"= "Residential Class Seg: Total Population",
  "multigroupd_education_rac:percent_white"= "Residential Class Seg: %White",
  "multigroupd_education_rac:delta_nonwhite_white_unemployed"= "Residential Class Seg: Diff White-Nonwhite Unemployment",
  "multigroupd_education_rac:gini"= "Residential Class Seg:Gini",
  "multigroupd_education_rac:percent_unemployed"= "Residential Class Seg:%Unemployment",
  
  
  
  ### educational seg and interaction with modifiers  ACS edition
  "multigroupd_education_rac_acs:pct_workers_age55_older"="Residential Class Seg:% 55+years",
  "multigroupd_education_rac_acs:pct_workers_income1250_less"="Residential Class Seg:% Income<1250", 
  "multigroupd_education_rac_acs:pct_workers_white"="Residential Class Seg:% White", 
  "multigroupd_education_rac_acs:pct_workers_education_college"="Residential Class Seg:% College Educated", 
  "multigroupd_education_rac_acs:pct_workers_education_lesshighschool"="Residential Class Seg:% Less than High School",
  "multigroupd_education_rac_acs:pct_workers_AgriMiningUtilCons"="Residential Class Seg:% Work in Agriculture/ Mining etc", 
  "multigroupd_education_rac_acs:pct_workers_Manuf"="Residential Class Seg:% Work in Manufacturing", 
  "multigroupd_education_rac_acs:pct_workers_TradeCommerceTransport"="Residential Class Seg:% Work in Trade/Commerce/Transport",
  "multigroupd_education_rac_acs:pct_workers_InfoFinProf_services"="Residential Class Seg:% Work in Professional Services",
  "multigroupd_education_rac_acs:pct_workers_PublicSocial_services"="Residential Class Seg:% Work in Public/Social Services",
  "multigroupd_education_rac_acs:pct_workers_Entertainment"="Residential Class Seg:% Work in Entertainment/Recreation",
  
  'multigroupd_education_rac_acs:average_time_work'="Residential Class Seg:Work commute (mins)", 
  "multigroupd_education_rac_acs:percent_publictransport"="Residential Class Seg:%commuters using transit",
  "multigroupd_education_rac_acs:delta_pct_ptcar_longcommute" ="Residential Class Seg:Diff in %commutes>=45min",
  "multigroupd_education_rac_acs:popdensity_1000persqkm"= "Residential Class Seg:Pop Density",
  "multigroupd_education_rac_acs:pct_carcommutes_over45m"="Residential Class Seg:% car commutes >=45min",
  "multigroupd_education_rac_acs:pct_ptcommutes_over45m"="Residential Class Seg:% PT commutes >=45min",
  
  "multigroupd_education_rac_acs:total_pop"= "Residential Class Seg: Total Population",
  "multigroupd_education_rac_acs:percent_white"= "Residential Class Seg: %White",
  "multigroupd_education_rac_acs:delta_nonwhite_white_unemployed"= "Residential Class Seg: Diff White-Nonwhite Unemployment",
  "multigroupd_education_rac_acs:gini"= "Residential Class Seg:Gini",
  "multigroupd_education_rac_acs:percent_unemployed"= "Residential Class Seg:%Unemployment",
  
  "as.factor(year)2012"="Year 2012",
  "as.factor(year)2013"="Year 2013",
  "as.factor(year)2014"="Year 2014",         
  "as.factor(year)2015"="Year 2015",
  "as.factor(year)2016"="Year 2016",
  "as.factor(year)2017"="Year 2017",
  "as.factor(year)2018" ="Year 2018")

